### ISSUE TITLE
XSS STORED - OSINT.SH ( PUBLIC BUCKETS )

### ISSUE THREAD

**Issue by NyenderID** [secgron/osint.sh#1]
![Screenshot_9](https://user-images.githubusercontent.com/20701798/107785817-a0bdce80-6d7f-11eb-9f2f-4f93ffb0fd32.png)
**Describe the bug**
XSS STORED - OSINT.SH ( PUBLIC BUCKETS )

**To Reproduce**
1. Go to https://osint.sh/buckets/
2. Input the payload in Keyword or Ext
3. Check now

**Payload**
https://pastebin.com/raw/RyZJdj3U

**Comment by secgron** [comment]
Since there is no authentication in osint.sh I thought XSS would have no impact and it would be self XSS.

But thanks for taking time to find out. Patched!
