### ISSUE TITLE
"Zero Account Balance" - OSINT.SH (Whois History)

### ISSUE THREAD

**Issue by Madhour** [secgron/osint.sh#2]
**Describe the bug**
![image](https://user-images.githubusercontent.com/69970159/133943480-e27e1aab-d198-4646-8a2c-8676b69a4e95.png)
Each query returns "Zero Account Balance"

**To Reproduce**
1. Go to osint.sh/whoishistory
2. type in arbitrary domain and submit

**Browser:**
 - Firefox (Desktop and Smartphone)

**Comment by secgron** [comment]
It should now be back to normal. Please recheck.

Thank you
