### ISSUE TITLE
Connection timed out

### ISSUE THREAD

**Issue by mdsdtech** [secgron/osint.sh#4]
Cannot access the osint.sh. I think the domain expired? 

![IMG_20220723_114742](https://user-images.githubusercontent.com/70020155/180589392-92f13235-5de8-4374-9a8e-d8ae5e57e8ca.jpg)

**Comment by secgron** [comment]
It should now be back to normal. Please recheck.

Thank you

**Comment by mdsdtech** [comment]
Thank you for fix it. 👍
