### ISSUE TITLE
Gateway time-out

### ISSUE THREAD

**Issue by Northernside** [secgron/osint.sh#5]
Just wanted to note here, that osint.sh loads a long time when submitting requests (e.g. subdomain finder) and then a Gateway time-out error appears.
![image](https://user-images.githubusercontent.com/60970791/221555132-c1bd17be-038d-4399-9091-65860032376e.png)

**Comment by secgron** [comment]
It should now be back to normal. Please recheck.

Thank you

**Comment by Northernside** [comment]
Works, thank you :)

**Comment by Northernside** [comment]
Unfortunately, it fails again 👀
