### ISSUE TITLE
 "Zero Account Balance" - Whois History

### ISSUE THREAD

**Issue by asclepiadae** [secgron/osint.sh#8]
**Describe the bug**
Recurrance of #2 
All queries return "Zero Account Balance"

**To Reproduce**
1. Access [osint.sh/whoishistory](osint.sh/whoishistory)
2. Use any domain name (e.g. google.com)
3. Error appears instead of data

**Screenshots**
![image](https://github.com/secgron/osint.sh/assets/2826435/c405f609-f8d1-469a-896a-232424669601)

**Comment by secgron** [comment]
Solved.
